# Only trigger builds for master.
trigger:
  branches:
    include:
      - master

# Trigger pull request builds against master.
pr:
  autoCancel: true
  branches:
    include:
      - master

# Build roughly every other week.
# https://crontab.guru/#41_1_1,14_*_*
schedules:
  - cron: "41 1 1,14 * *"
    displayName: Cronomatic Bifurcated Build
    branches:
      include:
        - master
    always: true

jobs:
  ######################################################################################
  # Linux :: Python :: 3.6, 3.7, 3.8, 3.9                                              #
  ######################################################################################
  - job: Linux_Python
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: Linux
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: Linux
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.8
          image_short: Linux
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.9
          image_short: Linux
  ######################################################################################
  # macOS :: Python :: 3.6, 3.7, 3.8, 3.9                                              #
  ######################################################################################
  - job: macOS_Python
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: macOS
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: macOS
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.8
          image_short: macOS
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.9
          image_short: macOS
  ######################################################################################
  # Win64 :: Python :: 3.6, 3.7, 3.8, 3.9                                              #
  ######################################################################################
  - job: Win64_Python
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: Win64
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: Win64
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.8
          image_short: Win64
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.9
          image_short: Win64
  ######################################################################################
  # Linux :: Demos                                                                     #
  ######################################################################################
  - job: Linux_Demos
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: Linux
  ######################################################################################
  # macOS :: Demos                                                                     #
  ######################################################################################
  - job: macOS_Demos
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: macOS
  ######################################################################################
  # Win64 :: Demos                                                                     #
  ######################################################################################
  - job: Win64_Demos
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: Win64
  ######################################################################################
  # Linux :: docs, linkcheck                                                           #
  ######################################################################################
  - job: Docs_Linkcheck
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          architecture: 'x64'
        displayName: Use Python 3.9
      - script: |
          pip install -U tox
          tox -e docs,linkcheck
        displayName: Check Docs / Linkcheck
  ######################################################################################
  # Linux :: Provider Check                                                            #
  ######################################################################################
  - job: Provider_Check
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          architecture: 'x64'
        displayName: Use Python 3.9
      - script: |
          pip install -U pip
          pip install coverage codecov toml
        displayName: Install Dependencies
      - script: |
          coverage run ./tests/full_provider_test.py azure_pipelines
          coverage xml -o coverage.xml
          codecov --required -X gcov -f coverage.xml --name "[AzP] Full Provider Check" -t $(CODECOV_TOKEN)
        displayName: Verify Azure Pipelines is Detected
