# Only trigger builds for master.
trigger:
  branches:
    include:
      - master

# Trigger pull request builds against master.
pr:
  autoCancel: true
  branches:
    include:
      - master

# Build roughly every other week.
# https://crontab.guru/#41_1_1,14_*_*
schedules:
  - cron: "41 1 1,14 * *"
    displayName: Cronomatic Bifurcated Build
    branches:
      include:
        - master
    always: true

jobs:
  ######################################################################################
  # Linux :: Python :: 3.5, 3.6, 3.7                                                   #
  ######################################################################################
  - job: Linux_Python
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.5
          image_short: Linux
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: Linux
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: Linux
  ######################################################################################
  # macOS :: Python :: 3.5, 3.6, 3.7                                                   #
  ######################################################################################
  - job: macOS_Python
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.5
          image_short: macOS
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: macOS
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: macOS
  ######################################################################################
  # Win64 :: Python :: 3.5, 3.6, 3.7                                                   #
  ######################################################################################
  - job: Win64_Python
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.5
          image_short: Win64
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.6
          image_short: Win64
      - template: .ci/test_python_and_upload.yml
        parameters:
          py_version: 3.7
          image_short: Win64
  ######################################################################################
  # Linux :: Demos                                                                     #
  ######################################################################################
  - job: Linux_Demos
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: Linux
  ######################################################################################
  # macOS :: Demos                                                                     #
  ######################################################################################
  - job: macOS_Demos
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: macOS
  ######################################################################################
  # Win64 :: Demos                                                                     #
  ######################################################################################
  - job: Win64_Demos
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: .ci/run_demos.yml
        parameters:
          image_short: Win64
  ######################################################################################
  # Linux :: docs, linkcheck                                                           #
  ######################################################################################
  - job: Docs_Linkcheck
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
        displayName: Use Python 3.7
      - script: |
          pip install -U tox
          tox -e docs,linkcheck
        displayName: Check Docs / Linkcheck
