sudo: false
os: linux
dist: focal
group: edge
arch: arm64-graviton2
virt: lxd
language: python

# Only build master branch, other branches will have a Pull Request build.
branches:
  only:
    - master

matrix:
  include:
    - language: generic
      services:
        - docker
      before_install:
        - docker pull python:3.5.0
        - docker run -d --entrypoint /bin/sh --name py350 python:3.5.0
        - docker cp . py350:/data
      install:
        - docker exec py350 pip install -U pip
        - docker exec py350 pip install tox
      script:
        - docker exec --workdir /data py350 tox -e py -- --cov-report xml:coverage.xml --cov
        - docker cp py350:/data/coverage.xml .
        - docker stop py350
      after_success:
        - pip install codecov
        - codecov --required -X gcov -f coverage.xml --name "[Travis] docker-py3.5.0"
      env: PY=3.5.0
      # NOTE: using language: generic on xenial to specifically get 3.5.2, which
      # does not have NoReturn in typing.  Acquiring 3.5.0 on Ubuntu is
      # challenging even to build from source due to OpenSSL ABI changes.
    - language: generic
      dist: xenial
      addons:
        apt:
          packages:
            - python3.5
            - python3.5-dev
            - python3.5-venv
      before_install:
        - python3 -m venv venv
        - source venv/bin/activate
      env: PY=3.5
    - python: 3.6
      env: PY=3.6
    - python: 3.7
      env: PY=3.7
    - python: 3.8
      env: PY=3.8
    - python: 3.9
      env: PY=3.9
    - os: linux
      language: python
      python: 3.9
      env: TEST=lint
      script:
        - tox -e lint
      after_success:  # don't do uploading, no coverage data needed
        - echo

install:
  - pip install -U tox codecov
script:
  - tox -e py -- --cov-report xml:coverage.xml --cov
after_success:
  - py_xy="$(python -c 'import sys; print(".".join(str(n) for n in sys.version_info[0:2]))')"
  - codecov --required -X gcov -f coverage.xml --name "[Travis] $TRAVIS_OS_NAME-$py_xy"
