sudo: false
os: linux
dist: focal
group: edge
arch: arm64-graviton2
virt: lxd
language: python

# Only build master branch, other branches will have a Pull Request build.
branches:
  only:
    - master

matrix:
  include:
    - python: 3.6
      env: PY=3.6
    - python: 3.7
      env: PY=3.7
    - python: 3.8
      env: PY=3.8
    - python: 3.9
      env: PY=3.9
    - os: linux
      language: python
      python: 3.9
      env: TEST=lint
      script:
        - tox -e lint
      after_success:  # don't do uploading, no coverage data needed
        - echo

install:
  - pip install -U tox codecov
script:
  - tox -e py -- --cov-report xml:coverage.xml --cov
after_success:
  - py_xy="$(python -c 'import sys; print(".".join(str(n) for n in sys.version_info[0:2]))')"
  - codecov --required -X gcov -f coverage.xml --name "[Travis] $TRAVIS_OS_NAME-$py_xy"
